---
- name: 删除cephblockpools类型的所有CR实例
  kubernetes.core.k8s:
    kind: CephBlockPool
    namespace: "{{ ceph_namespace }}"
    state: absent
    all: true  # 删除该命名空间下所有CephBlockPool实例
    wait: yes
    wait_timeout: 180  # 延长超时时间
  ignore_errors: yes
  run_once: yes

# 2. 移除CRD的Finalizer（若存在阻塞）
- name: 移除cephblockpools CRD的Finalizer
  kubernetes.core.k8s:
    kind: CustomResourceDefinition
    name: cephblockpools.ceph.rook.io
    state: present  # 用present执行patch操作
    definition:
      metadata:
        finalizers: null  # 清空Finalizer
  ignore_errors: yes
  run_once: yes

# 3. 最终删除CRD
- name: 删除cephblockpools CRD
  kubernetes.core.k8s:
    kind: CustomResourceDefinition
    name: cephblockpools.ceph.rook.io
    state: absent
    wait: yes
    wait_timeout: 180  # 延长超时时间，确保清理完成
  ignore_errors: yes
  run_once: yes

- name: 删除Rook相关ReplicaSet
  kubernetes.core.k8s:
    kind: ReplicaSet
    namespace: "{{ ceph_namespace }}"
    state: absent
    wait: yes
  ignore_errors: yes
  run_once: yes  # 只在控制节点执行一次

- name: 删除Rook相关DaemonSet
  kubernetes.core.k8s:
    kind: DaemonSet
    namespace: "{{ ceph_namespace }}"
    state: absent
    wait: yes
  ignore_errors: yes
  run_once: yes  # 只在控制节点执行一次



- name: 清理 ceph 命名空间下的所有 Deployment
  kubernetes.core.k8s:
    kind: Deployment
    namespace: "{{ ceph_namespace }}"
    state: absent
    wait: yes
    all: true  # 删除该命名空间下所有 Deployment
  run_once: true  # 仅在控制节点执行（与现有部署逻辑一致）
  ignore_errors: true


- name: 清理 ceph 命名空间下的所有 Pod
  kubernetes.core.k8s:
    kind: Pod
    namespace: "{{ ceph_namespace }}"
    state: absent
    wait: yes
    all: true  # 删除该命名空间下所有 Pods
  run_once: true  # 仅在控制节点执行（与现有部署逻辑一致）
  ignore_errors: true

- name: 清理 ceph 命名空间下的所有 Job
  kubernetes.core.k8s:
    kind: Job
    namespace: "{{ ceph_namespace }}"
    state: absent
    wait: yes
    all: true  # 删除该命名空间下所有 Job
  run_once: true  # 仅在控制节点执行（与现有部署逻辑一致）
  ignore_errors: true


- name: 清理 ceph 命名空间下的所有 Service
  kubernetes.core.k8s:
    kind: Service
    namespace: "{{ ceph_namespace }}"
    state: absent
    wait: yes
    all: true  # 删除该命名空间下所有 Service
  run_once: true  # 仅在控制节点执行（与现有部署逻辑一致）
  ignore_errors: true

- name: 清理节点上的Rook数据目录
  file:
    path: "{{ item }}"
    state: absent
    force: yes
  loop:
    - /var/lib/rook
    - /etc/rook
    - /var/run/ceph
    - /var/log/ceph
    - /tmp/rook

- name: 清理完成提示
  debug:
    msg: "Rook Ceph集群清理完成，所有相关资源和数据已移除"
  run_once: yes  # 只在控制节点显示一次

- name: 分发 Rook 部署文件
  copy:
    src: "examples/"
    dest: "/tmp/rook-deploy/"
    mode: '0644'

- name: 清理 ceph crds.yaml
  kubernetes.core.k8s:
    src: "/tmp/rook-deploy/crds.yaml"
    state: absent
    wait: yes
  run_once: true

- name: 清理 ceph common.yaml
  kubernetes.core.k8s:
    src: "/tmp/rook-deploy/common.yaml"
    state: absent
    wait: yes
  run_once: true

- name: 清理 ceph csi-operator.yaml
  kubernetes.core.k8s:
    src: "/tmp/rook-deploy/csi-operator.yaml"
    state: absent
    wait: yes
  run_once: true

- name: 清理 ceph operator.yaml
  kubernetes.core.k8s:
    src: "/tmp/rook-deploy/operator.yaml"
    state: absent
    wait: yes
  run_once: true

- name: 创建 ceph 命名空间
  kubernetes.core.k8s:
    name: "{{ ceph_namespace }}"
    kind: Namespace
    api_version: v1
    state: present
    wait: yes
  run_once: true



- name: 复制 ceph serviceAccount 部署文件
  copy:
    src: "files/ceph-serviceaccount.yaml"
    dest: "/tmp/rook-deploy/ceph-serviceaccount.yaml"
  run_once: true

- name: 部署 ceph serviceAccount
  kubernetes.core.k8s:
    src: "/tmp/rook-deploy/ceph-serviceaccount.yaml"
    state: present
    wait: yes
  run_once: true

- name: 部署 ceph crds.yaml
  kubernetes.core.k8s:
    src: "/tmp/rook-deploy/crds.yaml"
    state: present
  run_once: true

- name: 部署 ceph common.yaml
  kubernetes.core.k8s:
    src: "/tmp/rook-deploy/common.yaml"
    state: present
  run_once: true

- name: 部署 ceph csi-operator.yaml
  kubernetes.core.k8s:
    src: "/tmp/rook-deploy/csi-operator.yaml"
    state: present
  run_once: true

- name: 部署 ceph operator.yaml
  kubernetes.core.k8s:
    src: "/tmp/rook-deploy/operator.yaml"
    state: present
  run_once: true

- name: 等待 Rook Operator 就绪
  shell: kubectl wait --for=condition=ready pod -l app=rook-ceph-operator -n {{ ceph_namespace }}  --timeout=300s
  run_once: true

- name: 生成 Ceph 集群配置文件
  template:
    src: cluster-single-node.j2
    dest: /tmp/rook-deploy/cluster.yaml
    mode: '0644'
  run_once: true

- name: 清理 Ceph 集群
  kubernetes.core.k8s:
    src: "/tmp/rook-deploy/cluster.yaml"
    state: absent
  run_once: true

- name: 部署 Ceph 集群
  kubernetes.core.k8s:
    src: "/tmp/rook-deploy/cluster.yaml"
    state: present
  run_once: true

- name: "检测 Rook-Ceph Operator 就绪状态"
  kubernetes.core.k8s_info:
    kind: "Deployment"
    namespace: "rook-ceph"
    label_selectors: ["app=rook-ceph-operator"]
  register: operator_status
  until: >
    operator_status.resources[0].status.readyReplicas | default(0) == 
    operator_status.resources[0].spec.replicas | default(0)
  retries: 30
  delay: 10
  run_once: true


- name: 部署存储类 csi/rbd/storageclass.yaml
  kubernetes.core.k8s:
    src: "/tmp/rook-deploy/csi/rbd/storageclass.yaml"
    state: present
  run_once: true

- name: 部署存储类 csi/cephfs/storageclass.yaml
  kubernetes.core.k8s:
    src: "/tmp/rook-deploy/csi/cephfs/storageclass.yaml"
    state: present
  run_once: true

