---
mysqld_exporter:
  mysql_user: "root"  # 你的MySQL用户名
  mysql_password: "!qaz2Wsx"  # 你的MySQL密码
  mysql_addr: "mysql-5-7-44-headless.kube.svc.cluster.local:3306"  # 你的MySQL地址+端口




process_exporter:
  - { "name": "kube-apiserver", "cmd": "kube-apiserver" }
  - { "name": "kube-controller-manager", "cmd": "kube-controller-manager" }
  - { "name": "kube-scheduler", "cmd": "kube-scheduler" }
  - { "name": "prometheus-server", "cmd": "prometheus" }
  - { "name": "alertmanager", "cmd": "alertmanager" }
  - { "name": "grafana", "cmd": "grafana-server" }