---
- name: 创建 Prometheus 命名空间
  kubernetes.core.k8s:
    name: prometheus
    kind: Namespace
    api_version: v1
    state: present
  run_once: true

- name: 复制 alert-rules.yaml 部署文件
  copy:
    src: "files/alert-rules.yaml"
    dest: "/tmp/alert-rules.yaml"
  run_once: true


- name: 创建包含 alert-rules.yaml 的 ConfigMap
  kubernetes.core.k8s:
    kind: ConfigMap
    name: prometheus-alert-rules
    namespace: prometheus
    state: present
    definition:
      data:
        alert_rules.yml: "{{ lookup('file', '/tmp/alert-rules.yaml') }}"
  run_once: true

- name: 复制 Prometheus serviceAccount 部署文件
  copy:
    src: "files/prometheus-serviceaccount.yaml"
    dest: "/tmp/prometheus-serviceaccount.yaml"
  run_once: true

- name: 部署 Prometheus serviceAccount
  kubernetes.core.k8s:
    src: "/tmp/prometheus-serviceaccount.yaml"
    state: present
  run_once: true

- name: 复制 Prometheus rbac 部署文件
  copy:
    src: "files/prometheus-rbac.yaml"
    dest: "/tmp/prometheus-rbac.yaml"
  run_once: true

- name: 部署 Prometheus rbac
  kubernetes.core.k8s:
    src: "/tmp/prometheus-rbac.yaml"
    state: present
  run_once: true


- name: 复制 Prometheus 部署文件
  copy:
    src: "files/prometheus-deploy.yaml"
    dest: "/tmp/prometheus-deploy.yaml"
  run_once: true

- name: 创建 Prometheus 存储目录(/data/prometheus)
  ansible.builtin.file:
    path: /data/prometheus
    state: directory
    mode: '0777'
    recurse: yes
  run_once: true

- name: 部署 Prometheus
  kubernetes.core.k8s:
    src: "/tmp/prometheus-deploy.yaml"
    state: present
  run_once: true

