---
- include_tasks: 00_check_kubernetes.yml
- include_tasks: 01_deploy_prometheus_images.yml
- include_tasks: 02_deploy_prometheus.yml
- include_tasks: 03_deploy_grafana.yml
- include_tasks: 04_deploy_dashboards.yml